blog/apps/myblog/urls.py
from django.urls import path

from . import views

app_name='myblog'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:article_id>/', views.detail, name = 'detail')

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('myblog.urls')), 
    path('admin/', admin.site.urls),
]

blog/apps/myblog/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField('Название статьи', max_length = 200)
    text  = models.TextField('Текст статьи')
    pub_date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('Имя автора', max_length = 50)
    comment_text = models.CharField('Текст комментария', max_length = 200)

blog/apps/myblog/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from .models import Article, Comment

def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'myblog/list.html', {'latest_articles_list' : latest_articles_list})

def detail(request, article_id):
    try:
        a = Article.objects.get(id = article_id)
        print(a)
    except:
        raise Http404('Статья не найдена!')

    return render(request, 'myblog/detail.html', {'article': a})

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Мой сайт {% endblock %}</title>
    </head>

    <body>
        {% block content %} {% endblock %}
    </body>
</html>

blog/templates/myblog/detail.html
{% extends 'base.html' %}

{% block title %} {{article.title}} {% endblock %}

{% block content %}

    <h2>{{article.title}}</h2>

    <p>{{article.text}}</p>

    <em>{{article.pub_date}}</em>

{% endblock %}

blog/templates/myblog/list.html
{% extends 'base.html' %}

{% block title %} Последние статьи {% endblock %}

{% block content %}

    {% if latest_articles_list %}
        {% for a in latest_articles_list %}
            <a href="{% url 'myblog:detail' a.id %}">{{a.title}}</a>

        {% endfor %}
    {% else %}
        Статьи не найдены

    {% endif %}

{% endblock %}